SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
FPS = 30
LIVES = 3
JUMP_HEIGHT = 150  # Maximum jump height
MOVE_SPEED = 5 # Left / Right move speed
RECT_WIDTH = 100
RECT_INITIAL_HEIGHT = 50
REDUCE_SPEED = 5 # FPS the reduce_amount 
REDUCE_AMOUNT = 10
FALLING_SPEED = 1  # Speed at which the llama falls